/* external copy of the variables                                             */

extern char  golden_path[127];
extern char  golden_path_drive[5];

extern char  call_editor[101];
extern char  call_pager[101];
extern char  call_vocplayer[101];
extern char  call_voc2wav[101];

extern char  fns_drive[MAXDRIVE];
extern char  fns_dir[MAXDIR];
extern char  fns_fname[MAXFILE];
extern char  fns_ext[MAXEXT];
extern char  fns_ext2[MAXEXT];

extern char  df_inst_dir[81];
extern char  dark_gob[101];
extern char  textures_gob[101];
extern char  sprites_gob[101];
extern char  sounds_gob[101];

extern char  bm_data_dir[81];
extern char  fme_data_dir[81];
extern char  wax_data_dir[81];
extern char  vo_data_dir[81];
extern char  pa_data_dir[81];
extern char  pa_file[20];
extern char  lv_data_dir[81];
extern int   level_selected;
extern char  level_name[9];
extern char  fname[80];
extern char  fname_lev[80];
extern char  fname_pal[80];
extern char  fname_inf[80];
extern char  fname_gol[80];
extern char  fname_o[80];
extern long  counter;

extern char  BGIdriver[10];
extern int   BGImode;
extern int   gdriver;
extern int   gmode;
extern int   errorcode;

extern char  tmpstr[80];
extern int   ccc;
extern int   TEST_AS_GOB            ;
extern int   MENU_FORE              ;
extern int   MENU_BACK              ;
extern int   MENU_BORDER            ;
extern int   MENU_DIR               ;
extern int   COLOR_ERASER           ;

extern int   PICK_FORE              ;
extern int   PICK_BACK              ;
extern int   PICK_BORDER            ;
extern int   PICK_HILITE            ;

extern int   EDIT_FORE              ;
extern int   EDIT_BACK              ;
extern int   EDIT_CURSOR            ;

extern int   EDIT_ALLOWED           ;
extern int   EDIT_LEV_ALLOWED       ;

extern char  DACbuffer[768];

extern int   OUT_X, OUT_Y;
